version: '3.8'
services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ../.data:/data/db
    ports:
      - "27017:27017"
    restart: always
  zootplusbackend:
    image: ghcr.io/zoot-plus/zootplusbackend:latest
    container_name: ZootPlusBackend
    command: --spring.profiles.active=prod
    ports:
      - "8080:8080"
    volumes:
      - ./application-prod.yml:/app/application-prod.yml:ro
    links:
      - redis
      - mongo
    restart: always
    depends_on:
      - redis
      - mongo
